### ISSUE TITLE
请问如何获取伯乐在线之前的翻译文稿？

### ISSUE THREAD

**Issue by pi1ot** [jobbole/translation-warehouse#180]
在网上搜到一些伯乐在线的翻译稿转载，内容不够完整，译者署名是乔永琪，请问是否有办法获取到原稿或者联系到译者？多谢。

**Comment by H4M5TER** [comment]
伯乐在线的微信公众号还在维护，可以去那里找找

**Comment by H4M5TER** [comment]
以前挺爱看伯乐在线的，现在网站没了很多文章看不到了很可惜，可以把之前的翻译稿也上传到GitHub吗 @hanxiaomax

**Comment by pi1ot** [comment]
> 伯乐在线的微信公众号还在维护，可以去那里找找

搜过找不到了

**Comment by hanxiaomax** [comment]
@H4M5TER @pi1ot 我也不知道为什么不再维护了。之前的应该是没有了，后面在 Github 上面翻译的都在这里。不知道你说的具体是哪篇，我可以帮你找找

**Comment by pi1ot** [comment]
@hanxiaomax 我已经在webarchive上找到了大部分信息，多谢了
