### ISSUE TITLE
译者申请

### ISSUE THREAD

**Issue by nangua1995** [jobbole/translation-warehouse#7]
1.  擅长领域：数据挖掘/数据可视化/大数据
2. 在职/在校：在职
3. 每周的空闲时间：一整天
4. 有无翻译经验（如果有，欢迎附上链接）：无
5. 从何处了解到伯乐在线翻译组/为何加入：csdn 希望把更多的优秀的英文作品翻译成中文，推动国内外科技软件领域的交流。
6. 简单自我介绍：
-----------Hello,my name is BaiHe.I am an
 emploee of samsung elctrioncs and i want to improve my language skills as well  make more friends.thanks.

ps: 提交issue后，请发送issue链接到hanxiaomax@qq.com领取试译文章

@hanxiaomax

**Comment by hanxiaomax** [comment]
@nangua1995 试译已发送

**Comment by hanxiaomax** [comment]
@nangua1995 approved
